export const FETCH_USER_CART_ITEMS_REQUEST = "FETCH_USER_CART_ITEMS_REQUEST";
export const FETCH_USER_CART_ITEMS_SUCCESS = "FETCH_USER_CART_ITEMS_SUCCESS";
export const FETCH_USER_CART_ITEMS_FAILED = "FETCH_USER_CART_ITEMS_FAILED";

export const SET_CART_ITEMS = "SET_CART_ITEMS";
export const SET_CART_ITEMS_COUNT = "SET_CART_ITEMS_COUNT";

export const ADD_PRODUCT_TO_CART_REQUEST = "ADD_PRODUCT_TO_CART_REQUEST";
export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS";
export const ADD_PRODUCT_TO_CART_FAILED = "ADD_PRODUCT_TO_CART_FAILED";

export const SET_CHECKOUT_MODAL_DATA = "SET_CHECKOUT_MODAL_DATA";

export const REMOVE_PRODUCT_FROM_CART_REQUEST =
	"REMOVE_PRODUCT_FROM_CART_REQUEST";
export const REMOVE_PRODUCT_FROM_CART_SUCCESS =
	"REMOVE_PRODUCT_FROM_CART_SUCCESS";
export const REMOVE_PRODUCT_FROM_CART_FAILED =
	"REMOVE_PRODUCT_FROM_CART_FAILED";

export const CLOSE_PROCEED_TO_CHECKOUT_MODAL =
	"CLOSE_PROCEED_TO_CHECKOUT_MODAL";
