export const ADD_PRODUCT_TO_CART_REQUEST = "ADD_PRODUCT_TO_CART_REQUEST";
export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS";
export const ADD_PRODUCT_TO_CART_FAILED = "ADD_PRODUCT_TO_CART_FAILED";

export const REMOVE_PRODUCT_FROM_CART_REQUEST =
	"REMOVE_PRODUCT_FROM_CART_REQUEST";
export const REMOVE_PRODUCT_FROM_CART_SUCCESS =
	"REMOVE_PRODUCT_FROM_CART_SUCCESS";
export const REMOVE_PRODUCT_FROM_CART_FAILED =
	"REMOVE_PRODUCT_FROM_CART_FAILED";

export const CLOSE_PROCEED_TO_CHECKOUT_MODAL =
	"CLOSE_PROCEED_TO_CHECKOUT_MODAL";
