export const FETCH_USERS_WISHLIST_REQUEST = "FETCH_USERS_WISHLIST_REQUEST";
export const FETCH_USERS_WISHLIST_SUCCESS = "FETCH_USERS_WISHLIST_SUCCESS";
export const FETCH_USERS_WISHLIST_FAILED = "FETCH_USERS_WISHLIST_FAILED";

export const SET_WISHLIST_ITEMS = "SET_WISHLIST_ITEMS";
export const SET_WISHLIST_ITEMS_COUNT = "SET_WISHLIST_ITEMS_COUNT";

export const ADD_PRODUCT_TO_WISHLIST_REQUEST =
	"ADD_PRODUCT_TO_WISHLIST_REQUEST";
export const ADD_PRODUCT_TO_WISHLIST_SUCCESS =
	"ADD_PRODUCT_TO_WISHLIST_SUCCESS";
export const ADD_PRODUCT_TO_WISHLIST_FAILED = "ADD_PRODUCT_TO_WISHLIST_FAILED";

export const REMOVE_PRODUCT_FROM_WISHLIST_REQUEST =
	"REMOVE_PRODUCT_FROM_WISHLIST_REQUEST";
export const REMOVE_PRODUCT_FROM_WISHLIST_SUCCESS =
	"REMOVE_PRODUCT_FROM_WISHLIST_SUCCESS";
export const REMOVE_PRODUCT_FROM_WISHLIST_FAILED =
	"REMOVE_PRODUCT_FROM_WISHLIST_FAILED";
