export const FETCH_PINCODE_DETAILS_REQUEST = "FETCH_PINCODE_DETAILS_REQUEST";
export const FETCH_PINCODE_DETAILS_SUCCESS = "FETCH_PINCODE_DETAILS_SUCCESS";
export const FETCH_PINCODE_DETAILS_FAILED = "FETCH_PINCODE_DETAILS_FAILED";

export const SAVE_SHIPPING_DETAILS = "SAVE_SHIPPING_DETAILS";

export const INITIATE_PAYMENT_REQUEST = "INITIATE_PAYMENT_REQUEST";
export const INITIATE_PAYMENT_SUCCESS = "INITIATE_PAYMENT_SUCCESS";
export const INITIATE_PAYMENT_FAILED = "INITIATE_PAYMENT_FAILED";
