export const FETCH_PINCODE_DETAILS_REQUEST = "FETCH_PINCODE_DETAILS_REQUEST";
export const FETCH_PINCODE_DETAILS_SUCCESS = "FETCH_PINCODE_DETAILS_SUCCESS";
export const FETCH_PINCODE_DETAILS_FAILED = "FETCH_PINCODE_DETAILS_FAILED";

export const SAVE_SHIPPING_DETAILS = "SAVE_SHIPPING_DETAILS";

export const MAKE_PAYMENT_REQUEST = "MAKE_PAYMENT_REQUEST";
export const MAKE_PAYMENT_SUCCESS = "MAKE_PAYMENT_SUCCESS";
export const MAKE_PAYMENT_FAILED = "MAKE_PAYMENT_FAILED";
