export const FETCH_ALL_PRODUCTS_REQUEST = "FETCH_ALL_PRODUCTS_REQUEST";
export const FETCH_ALL_PRODUCTS_SUCCESS = "FETCH_ALL_PRODUCTS_SUCCESS";
export const FETCH_ALL_PRODUCTS_FAILED = "FETCH_ALL_PRODUCTS_FAILED";

export const FETCH_PRODUCT_BY_SLUG_REQUEST = "FETCH_PRODUCT_BY_SLUG_REQUEST";
export const FETCH_PRODUCT_BY_SLUG_SUCCESS = "FETCH_PRODUCT_BY_SLUG_SUCCESS";
export const FETCH_PRODUCT_BY_SLUG_FAILED = "FETCH_PRODUCT_BY_SLUG_FAILED";
